version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Flake8
          command: flake8 --per-file-ignores="__init__.py:F401" ./
      - run:
          name: Run tests
          command: pytest test/


workflows:
  sample:
    jobs:
      - build-and-test
